project:
  type: book
  output-dir: docs

book:
  title: "Analysis of the 2020 and 2022 General Elections of Clark and Washoe Counties, Nevada"
  author: "Edward Solomon"
  date: "28.8.2023"
  chapters:
    - index.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



