#######################################################################################################################################################
options(scipen=999)
set.seed(1)
library(ManifoldDestiny)
library(dplyr)
library(ggplot2)
library(plotly)
library(htmltools)
library(gridExtra)
library(shiny)
library(DT)
library(kableExtra)
library(htmlTable)
library(usethis)
source(paste0(rprojroot::find_rstudio_root_file(),'/R/misc.R'))
source(paste0(rprojroot::find_rstudio_root_file(),'/R/realregression.R'))
source(paste0(rprojroot::find_rstudio_root_file(),'/R/countingprocess.R'))
source(paste0(rprojroot::find_rstudio_root_file(),'/R/simulations.R'))
source(paste0(rprojroot::find_rstudio_root_file(),'/R/voterrollanalysis.R'))
P  <- c(1,2,3,4,5,6)
S  <- c(60,60,60,60,60,60)
T  <- c(40,40,40,40,40,40)
U  <- c(40,40*2,40*3,40*4,40*5,40*6)
V  <- c(60,60*2,60*3,40*4,40*5,40*6)
Up <- c(40,40*2-5,40*3-15,40*4,40*5,40*6)
Vp <- c(60,60*2+5,60*3+15,40*4,40*5,40*6)
R  <- c(200,200*2,200*3,200*4,200*5,200*6)
pro_rec_ex1 <- data.frame(P=c(1,2,3),S=S,T=T,U=U,V=V,R=R) 
pro_rec_ex2 <- data.frame(P=c(1,2,3),S=S,T=T,U=Up,V=Vp,R=R) 
pro_elc_ex1 <- Countinggraphs(pro_rec_ex1,polyn=1)
pro_elc_ex2 <- Countinggraphs(pro_rec_ex2,polyn=1)
debug(lapply(paste0("app",4:4), function(x){recoudatr(mda=md[[x]])}))
#########################################################################################################################################################
md <- jsonlite::fromJSON(paste0(rprojroot::find_rstudio_root_file(),"/data-raw/metadata.json"))
app0 <- get(load(paste0(rprojroot::find_rstudio_root_file(),"/data/app0.rda")))
app0_rp <- selreport(app0,md$app0)
app_0_out <- seloutput(app0_rp)
app1_rp <- selreport(app1,md$app1)
app_1_out <- seloutput(app1_rp)
app2_rp <- selreport(app2,md$app2)
app_2_out <- seloutput(app2_rp)
app3_rp <- selreport(app2,md$app2)
app_3_out <- seloutput(app2_rp)
app4_rp <- selreport(app2,md$app2)
app_4_out <- seloutput(app2_rp)
##########################################################################################################################################################
